### PR TITLE
Detects if the plugin repository main branch is built correctly

### LINKED ISSUE #363: Add a probe for failing builds on the default branch
### Description

If the project has as `Jenkinsfile` in the root directory, the probe should obtain the build status published through the checks API, whether it fails on ci.jenkins.io or not.

Failing builds on the default branch are a good indicator, that the project is in a bad state and requires (maintainer) attention.

### PR DESCRIPTION
**Pull request by AayushSaini101**
### Description

Add a new probe to check whether the build failed on the the default branch or not.
Closes #363.

### Testing done

Added new test cases for testing the probe.
Ran the code locally and checked with multiple plugins (maintained, old and unmaintained ones) if the behaviour is correct.

```[tasklist]
### Submitter checklist
- [x] If an issue exists, it is well described and linked in the description
- [x] The description of this pull request is detailed and explain why this pull request is needed
- [ ] The changeset is on a specific branch. Using `feature/` for new feature, or improvements ; Using `fix/` for bug fixes ; Using `docs/` for any documentation changes.
- [ ] If required, the documentation has been updated
- [x] There is automated tests to cover the code change / addition or an explanation why there is no tests in the description.
```

### CODE REVIEW

File: core/src/test/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbeTest.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+
+    @Test
+    void shouldCorrectlyDetectMissingJenkinsfile() throws IOException {
+        final FailingBuildProbe probe = getSpy();
+        final Plugin plugin = mock(Plugin.class);
+        final ProbeContext ctx = mock(ProbeContext.class);
+        final Path repo = Files.createTempDirectory("foo");
+        when(ctx.getScmRepository()).thenReturn(Optional.of(repo));
+        assertThat(probe.apply(plugin, ctx)).withFailMessage("No JenkinsFile found");
+    }
```
Comment (alecharp) [inline core/src/test/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbeTest.java:32]: I think this is already taking care off by the Jenkinsfile probe.

What I think would be beneficial for this pull request is to validate the behaviour when we cannot get the run of the latest commit of the default branch, to make sure which "run" you are getting with the `iterator().next()`, if it's possible for the conclusion to be `null`.

File: core/src/main/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbe.java [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+import org.springframework.stereotype.Component;
+
+/**
+ * This probe checks whether build failed on Default Branch or not.
+ */
+@Component
+@Order(FailingBuildProbe.ORDER)
+public class FailingBuildProbe extends Probe {
+
+    public static final int ORDER = LastCommitDateProbe.ORDER + 100;
```
Comment (alecharp) [inline core/src/main/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbe.java:49]: Run it after the Jenkinsfile probe and you can use its result to make sure there is a Jenkinsfile present.

File: core/src/main/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbe.java [hunk 3]
```diff
@@ -0,0 +1,107 @@
...
+        final Path repository = context.getScmRepository().get();
+        try (Stream<Path> paths = Files.find(repository, 1, (file, $) ->
+            Files.isReadable(file) && "JenkinsFile".equals(file.getFileName().toString()))) {
+            return paths.findFirst()
+                .map(file -> this.success("Jenkinsfile found"))
+                .orElseGet(() -> this.error("No Jenkinsfile found"));
+        } catch (IOException e) {
+            return this.error(e.getMessage());
+        }
+    }
```
Comment (alecharp) [inline core/src/main/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbe.java:90]: This is doing the Jenkinsfile probe job again. Not sure this is necessary.

File: core/src/main/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbe.java [hunk 4]
```diff
@@ -0,0 +1,107 @@
...
+                String defaultBranch = repository.getDefaultBranch();
+                GHCommit commit = repository.getCommit(defaultBranch);
+                GHCheckRun checkRun = commit.getCheckRuns().iterator().next();
+                GHCheckRun.Conclusion conclusion = checkRun.getConclusion();
+
+                if (conclusion == GHCheckRun.Conclusion.FAILURE) {
+                    return this.success("Build Failed in Default Branch");
+                } else {
+                    return this.success("Build is Success in Default Branch");
+                }
```
Comment (alecharp) [inline core/src/main/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbe.java:71]: Those statements need to be tested.

File: core/src/main/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbe.java [hunk 5]
```diff
@@ -0,0 +1,107 @@
...
+
+/**
+ * This probe checks whether build failed on Default Branch or not.
+ */
+@Component
+@Order(FailingBuildProbe.ORDER)
+public class FailingBuildProbe extends Probe {
+
+    public static final int ORDER = LastCommitDateProbe.ORDER + 100;
+    public static final String KEY = "failing-buildingProbe";
```
Comment (alecharp) [inline core/src/main/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbe.java:50]:
```suggestion
    public static final String KEY = "default-branch-build-status";
```

**Review by alecharp — CHANGES_REQUESTED** [review]

File: core/src/test/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbeTest.java (hunk 1 above)
Comment (AayushSaini101) [reply core/src/test/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbeTest.java:32]: Thanks @alecharp Is the above logic to check the status of the default branch in the probe is not correct ?

Comment (alecharp) [reply core/src/test/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbeTest.java:32]: Do you mean https://github.com/jenkins-infra/plugin-health-scoring/pull/422/files#diff-ccfb769cc30831bdce2acc485da9fb8ffa7d11a932657c1528b75f02e58e7f04R60-R71? Probably.

**Comment by alecharp** [comment]
@AayushSaini101 Are you still interesting to drive this pull request?

**Comment by AayushSaini101** [comment]
> @AayushSaini101 Are you still interesting to drive this pull request?

Yes, @alecharp I can work on this. Will submit the changes by ASAP

**Comment by AayushSaini101** [comment]
Closing this @alecharp due to multiple accounts. Creating new one

**Comment by alecharp** [comment]
Please, stop doing that. Use the proper account from the start. You are wasting the review the discussion already started here.

**Comment by AayushSaini101** [comment]
> Please, stop doing that. Use the proper account from the start. You are wasting the review the discussion already started here.
Sorry, This was my last PR that contained issue due to multiple accounts, I have resolved the issues in the remaining ones.

File: core/src/main/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbe.java (hunk 5 above)
Comment (AayushSaini101) [reply core/src/main/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbe.java]: Done @alecharp

File: core/src/main/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbe.java (hunk 3 above)
Comment (AayushSaini101) [reply core/src/main/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbe.java]: Done @alecharp Removed and update the order

File: core/src/main/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbe.java (hunk 2 above)
Comment (AayushSaini101) [reply core/src/main/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbe.java]: Done @alecharp

File: core/src/main/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbe.java (hunk 4 above)
Comment (AayushSaini101) [reply core/src/main/java/io/jenkins/pluginhealth/scoring/probes/FailingBuildProbe.java]: @alecharp can you help me in the testing,  GHCommit ghCommit = new GHCommit(); i cannot set particular commits for testing. any kind of more generic way to test it

**Comment by alecharp** [comment]
@AayushSaini101 have you plan to attend this pull request?

**Comment by AayushSaini101** [comment]
> @AayushSaini101 have you plan to attend this pull request?

Sorry @alecharp for being late for this PR, I am working on the GSOC proposal for this project, I will try to complete by this week.

**Comment by AayushSaini101** [comment]
@alecharp Can you help me to write test case for the changes, I am not sure how can i test the changes properly

File: core/src/test/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbeTest.java
Comment (alecharp) [inline core/src/test/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbeTest.java:1]: Missing the license as well

**Comment by alecharp** [comment]
Please, do not force push branch on pull request that has already been reviewed.
Some of the commits were made with different user as well.

There is still no tests to validate the probe.

**Comment by AayushSaini101** [comment]
> Please, do not force push branch on pull request that has already been reviewed. Some of the commits were made with different user as well.
> 
> There is still no tests to validate the probe.

@alecharp I tried to push normally but cannot able to push even rebase and resolving the conflicts, there were multiple accounts in the last commits, may be the reason of this, I have tried many approaches to push normally but cannot, Sorry for this

**Comment by AayushSaini101** [comment]
After removing the multiple accounts commits, now i can able to push normally

File: core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbe.java [hunk 6]
```diff
@@ -0,0 +1,91 @@
...
+            }
+
+            final Optional<String> repositoryName = context.getRepositoryName();
+            final GHRepository ghRepository = context.getGitHub().getRepository(repositoryName.get());
+            GHCommit commit = ghRepository.getCommit(ucPlugin.defaultBranch());
+            GHCheckRun checkRun = commit.getCheckRuns().iterator().next();
+            Conclusion conclusion = checkRun.getConclusion();
+
+            if (conclusion == Conclusion.FAILURE) {
+                return this.success("Build Failed in Default Branch");
```
Comment (alecharp) [inline core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbe.java:68]:
```suggestion
                return this.success("Build failed in default branch");
```

File: core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbe.java [hunk 7]
```diff
@@ -0,0 +1,91 @@
...
+            } else {
+                return this.success("Build is Success in Default Branch");
```
Comment (alecharp) [inline core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbe.java:70]:
```suggestion
                return this.success("Build is successful in default branch");
```

File: core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbe.java [hunk 8]
```diff
@@ -0,0 +1,91 @@
...
+                return error("Plugin cannot be found in Update-Center.");
+            }
+            final String defaultBranch = ucPlugin.defaultBranch();
+            if (defaultBranch == null || defaultBranch.isBlank()) {
+                return this.error("No default branch configured for the plugin.");
+            }
+
+            final Optional<String> repositoryName = context.getRepositoryName();
+            final GHRepository ghRepository = context.getGitHub().getRepository(repositoryName.get());
+            GHCommit commit = ghRepository.getCommit(ucPlugin.defaultBranch());
```
Comment (alecharp) [inline core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbe.java:63]: Value already assigned to a variable, let's use it.

```suggestion
            GHCommit commit = ghRepository.getCommit(defaultBranch);
```

File: core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbe.java [hunk 9]
```diff
@@ -0,0 +1,91 @@
...
+            GHCheckRun checkRun = commit.getCheckRuns().iterator().next();
+            Conclusion conclusion = checkRun.getConclusion();
+
+            if (conclusion == Conclusion.FAILURE) {
+                return this.success("Build Failed in Default Branch");
+            } else {
+                return this.success("Build is Success in Default Branch");
+            }
+        } catch (Exception ex) {
```
Comment (alecharp) [inline core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbe.java:72]: If we catch `Exception`, it means to catch anything that could go wrong. And we wouldn't know what went wrong.
Please, be more specific than `Exception` and log the exception.

File: core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbe.java [hunk 10]
```diff
@@ -0,0 +1,91 @@
...
+import org.springframework.stereotype.Component;
+
+/**
+ * This probe checks whether build failed on Default Branch or not.
+ */
+@Component
+@Order(DefaultBranchBuildStatusProbe.ORDER)
+public class DefaultBranchBuildStatusProbe extends Probe {
+
+    public static final int ORDER = JenkinsCoreProbe.ORDER + 100;
```
Comment (alecharp) [inline core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbe.java:45]: Do we need to be executed after that probe?

File: core/src/test/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbeTest.java [hunk 11]
```diff
@@ -0,0 +1,171 @@
...
+    @Override
+    DefaultBranchBuildStatusProbe getSpy() {
+        return spy(DefaultBranchBuildStatusProbe.class);
+    }
+
+    @BeforeEach
+    public void init() {
+
+        probe = getSpy();
+    }
```
Comment (alecharp) [inline core/src/test/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbeTest.java:65]: Why do we need to have the probe in a field?

File: core/src/test/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbeTest.java [hunk 12]
```diff
@@ -0,0 +1,171 @@
...
+        final GitHub gitHub = mock(GitHub.class);
+        final GHRepository ghRepository = mock(GHRepository.class);
+        final GHCommit ghCommit = mock(GHCommit.class);
+        final GHCheckRun checkRun = mock(GHCheckRun.class);
+        final PagedIterable<GHCheckRun> checkrun = mock(PagedIterable.class);
+        final PagedIterator<GHCheckRun> checkIterator = mock(PagedIterator.class);
+        final Plugin plugin = mock(Plugin.class);
+        final ProbeContext ctx = mock(ProbeContext.class);
+
+        final GitHub gh = mock(GitHub.class);
```
Comment (alecharp) [inline core/src/test/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbeTest.java:83]: Already mocked on line 74.
```suggestion
```

File: core/src/test/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbeTest.java [hunk 13]
```diff
@@ -0,0 +1,171 @@
...
+                                        ZonedDateTime.now(),
+                                        List.of(),
+                                        0,
+                                        "42",
+                                        defaultBranch)),
+                        Map.of(),
+                        List.of()));
+        when(ctx.getGitHub()).thenReturn(gh);
+        when(ctx.getRepositoryName()).thenReturn(Optional.of(pluginRepo));
+        when(ctx.getGitHub()).thenReturn(gitHub);
```
Comment (alecharp) [inline core/src/test/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbeTest.java:104]: Unless.

**Review by alecharp — CHANGES_REQUESTED** [review]
I'm not sure you are convinced that what you did is correct. 
I'll wait for you to fix the test class before reviewing it again.

File: core/src/test/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbeTest.java (hunk 13 above)
Comment (AayushSaini101) [reply core/src/test/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbeTest.java:104]: @alecharp I didn't get you regarding this

Comment (alecharp) [reply core/src/test/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbeTest.java:104]: Yes, I meant useless. you already mock that class before.

**Comment by alecharp** [comment]
@AayushSaini101 do you think you will have time to complete this pull request?
